config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  root 'home#index'
  match 'home', controller: 'home', action: 'index', via: 'get'
  get "/about" => "home#about", :as => "about" 

  match 'medics/results', controller: 'medics', action: 'results', via: 'get'
  match 'medics/rating', controller: 'medics', action: 'rating', via: 'post'
  match 'medics/create_comment', controller: 'medics', action: 'create_comment', via: 'post'
  match 'medics/create_relevance', controller: 'medics', action: 'create_relevance', via: 'post'
  get "/medics/profile/:id" => "medics#profile", :as => "profile"
  get "/workunits_graph" => "medics#workunits_graph", :as => "workunits_graph"
  match '/confirmation/:id/:token_email', controller: 'users', action: 'confirmation_email', via: 'get'

  get "/medics/profile/:id/create_relevance" => "medics#create_relevance", :as => "create_relevance"
  get "/medics/profile/:id/to_report" => "medics#to_report", :as => "to_report"

  get "/users/:id/edit_password" => "users#edit_password", :as => "edit_password"
  patch "/users/:id/edit_password/update_password", to: "users#update_password"
  
  get "/comments/reports", controller: 'comments', action: 'reports', :as => "reported_comments"
  get "/comments/reactivate_comment" => "comments#reactivate", :as => "reactivate_comment"
  get "/comments/deactivate_comment" => "comments#deactivate", :as => "deactivate_comment"
  get "/comments/disable_report" => "comments#disable_report", :as => "disable_report"
    
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "desactivate_account" => "users#desactivate", :as => "desactivate_account"
  get "/users/:id/reactivate_account" => "users#reactivate", :as => "reactivate_account"
  get "/users/:id/desactivate_account" => "users#desactivate", :as => "desactivate_account_admin"
  post "/upload", controller: 'parsers', action: 'upload'

  get "contact" => "contact#new", :as => "contact"

  post "/parsers", controller: 'parsers', action: 'index', :as => "index_parser"
  
  get 'users/index'
  get 'users/new'

  post '/users/:id', to: 'users#show'
  get '/users/:id/edit', to: 'users#edit'

  patch '/users/:id', to: 'users#update'

  resources :users do
    put :updatePassword, on: :member
  end
  resources :sessions
  resources :home
  resources :parsers
  resources :contact
  resources :password_resets

end

app/models/medic.rb
require 'work_unit'

class Medic < ActiveRecord::Base
	belongs_to :work_unit
	has_many :schedules
	has_many :rating, through: :user
	has_many :comments

	def self.search(speciality, work_unit)

		if work_unit != "Informe a Região"
			@work_unit_instance = WorkUnit.find_by_name(work_unit)

			if(@work_unit_instance)
				if speciality != "Informe a Especialidade"
					where("speciality =  ? AND work_unit_id = ?", speciality,@work_unit_instance.id).all
				else
					where("work_unit_id = ?", @work_unit_instance.id).all
				end
			end

		elsif speciality != "Informe a Especialidade"
			where("speciality =  ?", speciality).all
		else
		    nil
		end
	end
end

app/controllers/medics_controller.rb
class MedicsController < ApplicationController

	
	helper_method :array_speciality, :array_medics_quantity

	def results
		@medics = Medic.search(params[:list_specility], params[:list_work_unit_name])
		if @medics
  			@medics
  		else
  			flash.now.alert="Escolha um campo."
  			render "home/index"
  		end
	end

	def profile
		@medic = Medic.find_by_id(params[:id])
		@work_unit = WorkUnit.find_by_id(@medic.work_unit_id)
		@average = calculate_average(@medic)
		@ratings = Rating.all.where(medic_id: @medic.id).size
	end

#graphs methods and actions
	
	def workunits_graph
		@medics_size = Array.new
		@unit_name = Array.new
		@work_unit = WorkUnit.all

		@work_unit.each do |work_unit|
			quantity = Medic.all.where(work_unit_id: work_unit.id).size
			@medics_size.push(quantity)
			@unit_name.push(work_unit.name)
		end
	end

	def array_speciality (id_work_unit)
		@medic = Medic.all.where(work_unit_id: id_work_unit)
		@speciality = Array.new
		@medic.each do |medic|
			unless @speciality.include?(medic.speciality)
				@speciality.push(medic.speciality)
			end
		end
		return @speciality
	end

	def array_medics_quantity (id_work_unit, array_speciality)
		@medic = Medic.all.where(work_unit_id: id_work_unit)
		@medics_size_speciality = Array.new
		array_speciality.each do |speciality|
			quantity = Medic.all.where(speciality: speciality, work_unit_id: id_work_unit).size
			@medics_size_speciality.push(quantity)
		end
		return @medics_size_speciality
	end
	
	def rating
		medic_id = params[:medic_id]
		@user = User.find_by_id(session[:remember_token])
		@medic = Medic.find_by_id(medic_id)

		if @user != nil
			rating_status = ""

			@rating = Rating.find_by_user_id_and_medic_id(@user.id, @medic.id)

			if @rating != nil
				update_rating(@rating , params[:grade])
				rating_status = 'Avaliação Alterada!'
			else
				create_rating(@user, @medic)
				rating_status = 'Avaliação Realizada com sucesso!'
			end
			redirect_to action:"profile",id: medic_id, notice: rating_status
		else
			redirect_to login_path, :alert => "O Usuário necessita estar logado"
		end
	end

  	def create_comment
		@user = User.find_by_id(session[:remember_token])
		@medic = Medic.find_by_id(params[:medic_id])

		if @user
			@comment = Comment.new(content: params[:content], date: Time.now,
				medic: @medic, user: @user, comment_status: true, report: false)

			@comment.save
			redirect_to profile_path(@medic)
		else
			redirect_to login_path, :alert => "O Usuário necessita estar logado"
		end
  	end



  	def create_relevance
  		@user = User.find_by_id(session[:remember_token])
  		@comment = Comment.find_by_id(params[:comment_id])

		if @user == nil
			redirect_to login_path, :alert => "O Usuário necessita estar logado"
		elsif @comment
  			@relevance = Relevance.find_by_user_id_and_comment_id(@user.id, @comment.id)

  			if @relevance
  				@relevance.update_attribute(:value, params[:value])
  			else
  				@relevance = Relevance.create(value: params[:value], user: @user, comment: @comment)
  			end
			redirect_to action:"profile",id: params[:medic_id]
  		end
  	end

  	def to_report
  		@comment = Comment.find_by_id(params[:comment_id])
  		if @comment.report == false
  			@comment.update_attribute(:report, true)
  		end
  		flash[:notice] = "Comentário reportado."
		
  		redirect_to action:"profile",id: params[:medic_id]
  	end

  	def ranking
  		@medics = Medic.order(average: :desc).limit(10)
  	end

  	private 

  		def create_rating(user, medic)
			@rating = Rating.new(grade: params[:grade], user: user, medic: medic, date: Time.new)
			@rating.save
	  	end

	  	def update_rating(rating,grade)
	  		if grade != "0"
				rating.update_attribute(:grade , grade)
            	rating.update_attribute(:date , Time.new)
            end
	  	end

	  	def calculate_average(medic)
	  		@ratings = Rating.all.where(medic_id: medic.id)

	  		if @ratings.size == 0
	  			return 0
	  		else
		  		sum = 0
		  		@ratings.each do |r|
		  			sum += r.grade
	  		end
	  			medic.update_attributes(:average => sum/(1.0*@ratings.size))
				return sum/(1.0*@ratings.size)
	  		end
	  	end
end

app/helpers/medics_helper.rb
module MedicsHelper
end

app/views/medics/_comment.html.erb
<div class="panel-body">
    <ul class="list-group">
    	
    	<% @treta.each do |comment| %>
            <li class="list-group-item">
                <div class="row">
                    <div class="col-xs-10 col-md-11">
                        <div class="comment-text">
                            <%= comment.content%>
                        </div>
                        <div>
                            <div class="mic-info">
                                By: <%= comment.user.username%> on <%= comment.date.strftime("%d de %B de %Y") %>
                            </div>
                        </div>
                        
                        <div class="action">
	                        Esse comentário foi útil? 
								<%= link_to " #{get_relevances(comment.id,true)}", create_relevance_path(:value => true, :comment_id => comment.id, :medic_id => @medic.id) , class: "fa fa-thumbs-up btn btn-primary"%>
								<%= link_to " #{get_relevances(comment.id,false)}", create_relevance_path(:value => false, :comment_id => comment.id, :medic_id => @medic.id) , class: "fa fa-thumbs-down btn btn-primary "%>
                        </div>
                    </div>
                </div>
            </li>
        <%end%>
    </ul>
</div>

app/views/medics/_quantity_medics_by_speciality.html.erb
<h3><%= @name %></h3>
<script type="text/javascript" charset="utf-8">
 
$(document).ready(function() {

  var chart = new Highcharts.Chart({

  chart: {
    renderTo: 'container<%=@id%>',
    type: 'bar'
  },
  plotOptions: {
    series: {
      pointWidth: 30
    }
  },
  title: {
    text: null
  },
  xAxis: {
    categories: <%= raw @array_speciality %>
  },
  yAxis: {
    title: {
      text: 'Número de Médicos'
    }
  },
  series: [
    {
    name: 'Quantidade de médicos',
    data: <%= @array_quantity_medics %>
    },
  ],
  });
});
</script>

<% if @array_speciality.size >= 30 && @array_speciality.size <= 45%>
	<div class="col-sm-7" id="container<%=@id%>" style="height:1820px"></div>
	<% elsif @array_speciality.size <= 15 && @array_speciality.size > 5%>
	<div class="col-sm-7" id="container<%=@id%>" style="height:680px"></div>
	<% elsif @array_speciality.size <= 5 && @array_speciality.size >=1%>
	<div class="col-sm-7" id="container<%=@id%>" style="height:280px"></div>
	<% elsif @array_speciality.size > 45 %>
	<div class="col-sm-7" id="container<%=@id%>" style="height:2780px"></div>
	<% else %>
	<div class="col-sm-7" id="container<%=@id%>" style="height:1080px"></div>
<% end %>

app/views/medics/_workunits_graph.html.erb
<script type="text/javascript" charset="utf-8">
 
$(document).ready(function() {

  var chart = new Highcharts.Chart({

  chart: {
    renderTo: 'container',
    type: 'bar'
  },
  plotOptions: {
    series: {
      pointWidth: 30
    }
  },
  title: {
    text: null
  },
  xAxis: {
    categories: <%= raw @unit_name %>
  },
  yAxis: {
    title: {
      text: 'Número de Médicos'
    }
  },
  series: [
    {
    name: 'Quantidade de médicos',
    data: <%= @medics_size %>
    },
  ],
  });
});
</script>

<div id="container" style="height:1080px"></div>

app/views/medics/index.html.erb
<body>
  <table>
    <tr>
      <th>Nome</th>
      <th>Registro</th>
      <th>Especialidade</th>
      <th>Unidade de trabalho</th>
      <th>Entrada</th>
      <th>Saída</th>
    </tr>
  <% @medics.each do |medic| %>
    <tr>
      <%medic.schedules.each do |schedule|%>
        <td><%= medic.name          %></td>
        <td><%= medic.registry      %></td>
        <td><%= medic.speciality %></td>
        <td><%= medic.work_unit.name %></td>
        <td><%=schedule.in%></td>
        <td><%=schedule.out%></td>
      <%end%>
    </tr>
  <% end %>
  </table>
</body>

app/views/medics/profile.html.erb
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class= "panel-body">
				<div class="col-lg-2">
					<%= image_tag "medico140x126.png", class: "img_responsive img-rounded" %>
					<%= form_tag("/medics/rating", method: "post") do %> 
							<input id="input-2a" class="rating" name="grade" data-min="0" data-max="5" data-step="1" data-stars=5 
		   					 	data-glyphicon="false">
		   					<%= hidden_field_tag :medic_id, @medic.id %>
							<%= submit_tag 'Avaliar' , class: 'btn btn-lg btn-success rating-button' %>
					<%end%>
				</div>
				<div class="col-lg-6">
					<table>
						<tr>
							<h3><%=@medic.name%></h3>
						</tr>
						<tr>
							<td> Especialidade: </td>
							<td><%=@medic.speciality%></td>
						</tr>
						<tr>
							<td> Departamento: </td>
							<td><%=@medic.department%></td>
						</tr>
						<tr>
							<td> Unidade de Trabalho: </td>
							<td><%=@work_unit.name%></td>
						</tr>
						<tr>
							<td> Avaliação Média: <%=@average%></td>
							<td> Número de Avaliações: <%=@ratings%></td>
							
						</tr>
					</table>
				</div>
				<div class="col-lg-1 col-lg-offset-3">
					<!-- Button trigger modal -->
					<button class="btn btn-primary btn-lg button-schedule" data-toggle="modal" data-target="#myModal" title="Escala">
				    <i class="fa fa-table"></i>
				  </button>
				    <!-- Modal -->
				    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				      <div class="modal-dialog">
				          <div class="modal-content">
				              <div class="modal-header">
				                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				                  <h4 class="modal-title" id="myModalLabel">
				                    Escala - <%= @medic.name%>
				                  </h4>
				              </div>
				              <div class="modal-body">
				                <table class="table table-striped table-bordered table-hover" id="dataTables">
				                  <thead>
				                    <tr>
				                      <th>Entrada</th>
				                      <th>Saída</th>
				                    </tr>
				                  </thead>
				                  <tbody>
				                    <%@medic.schedules.each do |schedule|%>
				                      <tr>
				                        <td><%= schedule.in.strftime("%d de %B de %Y, as %H:%M") %></td>
				                        <td><%= schedule.out.strftime("%d de %B de %Y, as %H:%M") %></td>
				                      </tr>
				                  <%end%>
				                  </tbody>
				                </table>
				              </div>                                      
				          </div>
				          <!-- /.modal-content -->
				      </div>
				      <!-- /.modal-dialog -->
				    </div>
				    <!-- /.modal -->
				</div>
			</div>
		</div>
		<div class="panel panel-default widget">
            <div class="panel-heading">
        		<h3 class="panel-title">
                    Comentários
                </h3>
                	
                <span class="label label-info">
                    <%= @medic.comments.size %></span>
            </div>
            <div class="panel-body">
            	<%= form_tag("/medics/create_comment", method: "post") do %> 
					<%if current_user%>
						<%= hidden_field_tag  :medic_id, @medic.id %>
						<div class="input-group">
							<%= text_field_tag :content, "", class: "form-control", maxlength: 300, placeholder: 'Escreva seu cometário aqui'%>
							<span class="input-group-btn">
								<%= submit_tag 'Enviar', class: "btn btn-primary" %>
							</span>
						</div>
					<%else%>
						<div class="input-group">
							<%= text_field_tag :content, "", class: "form-control", disabled: true, placeholder: 'Acesse sua conta para comentar.'%>
							<span class="input-group-btn">
								<%= submit_tag 'Enviar', class: "btn btn-primary", disabled: true %>
							</span>
						</div>
					<%end%>
				<%end%>
                <ul class="list-group">
                	<% @medic.comments.reverse_each do |comment| %>
                		<%if comment.comment_status == true%>
		                    <li class="list-group-item">
		                        <div class="row">
		                        	<%= link_to "", to_report_path(:comment_id => comment.id, :medic_id => @medic.id) , class: "fa fa-exclamation close report ",  data: { confirm: 'Você tem certeza?' }, :title=> "Denunciar"%>
		                            	
		                            	<div class="col-xs-10 col-md-11">
		                            	<%if comment.user.medic_type_status == true%>
		                            	 <div class="comment-text medic-comment">
		                                    <%= comment.content%>
		                                </div>
		                            	<% else %>
		                                <div class="comment-text">
		                                    <%= comment.content%>
		                                </div>
		                                <%end%>
		                                <div class="action mic-info ">
		                                	Feito por: <%= comment.user.username%> on <%= comment.date.strftime("%d de %B de %Y") %>
		                                	<br>
		                                	 Esse comentário foi útil?
		                                	<div class="btn-group" role="group" aria-label="..."> 
	      									<%= link_to " sim", create_relevance_path(:value => true, :comment_id => comment.id, :medic_id => @medic.id) , class: "fa fa-thumbs-up btn btn-default btn-xs"%>
	      									<%= link_to " não", create_relevance_path(:value => false, :comment_id => comment.id, :medic_id => @medic.id) , class: "fa fa-thumbs-down btn btn-default btn-xs"%>
	      									</div>
		                                </div>
		                            </div>
		                        </div>
		                    </li>
		                <% end %>
                    <% end %>
                    <% if @medic.comments.size == 0%>
                    	<li class="list-group-item">
                    		Não há Comentários.
                    	</li>
                    <% end %>
                </ul>
                
            </div>
        </div>

	</div>
</div>

<script>
	// initialize with defaults
	$("#input-2a").rating({
		clearButton: '<button class="btn btn-default" type="button"> Limpar </button>'
	});

    $(document).ready(function() {
        $('#dataTables').dataTable();
    });
</script>

app/views/medics/ranking.html.erb
<div class="table-responsive">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>#</th>
				<th>Nota</th>
				<th>Nome do médico</th>
				<th>Especialidade</th>
				<th>Unidade de trabalho</th>
			</tr>
		</thead>
		<tbody>
			<% @cont = 1%>
			<% @medics.each do |medic| %>
				<tr>
					<td><%= @cont %></td>
					<% @cont = @cont+1 %>
					<td><%= medic.average %></td>
					<td><%= link_to medic.name, profile_path(medic)%></td>
					<td><%= medic.speciality %></td>
					<td><%= medic.work_unit.name %></td>
				</tr>
			<% end %>
		</tbody>
</div>

app/views/medics/results.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.3/css/jquery.dataTables.css">
  <script>
    $(document).ready(function() {
        $('#dataTables-medic').dataTable();
    });
  </script>
</head>
<body>
  <br>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover" id="dataTables-medic">
              <thead>
                <tr>
                  <th>Nome</th>
                  <th>Especialidade</th>
                  <th>Unidade de trabalho</th>
                  <th>Nota</th>
                  <th>Escalas</th>
                </tr>
              </thead>
              <tbody>
                <% @medics.each do |medic| %>
                  <tr>
                      <td><%= link_to medic.name, profile_path(medic)%></td>
                      <td><%= medic.speciality %></td>
                      <td><%= medic.work_unit.name %></td>
                      <td><%= medic.average %></td>
                      <td>
                        <button class="btn btn-primary btn-lg button-schedule" data-toggle="modal" data-target="#myModal<%= medic.id %>" title="Escala">
                          <i class="fa fa-table"></i>
                        </button>
                        <div class="modal fade" id="myModal<%= medic.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                          <div class="modal-dialog">
                              <div class="modal-content">
                                  <div class="modal-header">
                                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                      <h4 class="modal-title" id="myModalLabel">
                                        Escala - <%= medic.name%>
                                      </h4>
                                  </div>
                                  <div class="modal-body">
                                    <table class="table table-striped table-bordered table-hover" id="dataTables-<%= medic.id %>">
                                      <thead>
                                        <tr>
                                          <th>Entrada</th>
                                          <th>Saída</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <%medic.schedules.each do |schedule|%>
                                          <tr>
                                            <td><%= schedule.in.strftime("%d de %B de %Y, as %H:%M")  %></td>
                                            <td><%= schedule.out.strftime("%d de %B de %Y, as %H:%M")  %></td>
                                          </tr>
                                      <%end%>
                                      </tbody>
                                    </table>
                                  </div>                                      
                              </div>
                              <!-- /.modal-content -->
                          </div>
                          <!-- /.modal-dialog -->
                        </div>
                        <!-- /.modal -->
                      </td>
                  </tr>
                  <script>
                    $(document).ready(function() {
                        $('#dataTables-<%= medic.id %>').dataTable();
                    });
                  </script>
                <% end %>
              </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/medics/workunits_graph.html.erb
<div class="col-sm-2">       
  <nav class="nav-sidebar">
    <div style="overflow: auto; height: 530px">
		  <ul class="nav tabs">
        <li class="active"><a href="#tab170" data-toggle="tab">Médicos por Unidade</a></li>
        <hr>   
          <table>
            <li class="">
              <% @work_unit.each do |work_unit| %>
                <tr>
                  <% if work_unit.name == "DRS CANDANGOL./BAND/RIAC.FUNDO"%>
                    <li class="">
                      <a href="#tab<%= work_unit.id %>" data-toggle="tab">DRS CANDANGOL./ BAND/ RIAC.FUNDO</a>
                    </li>
                  <% else %>
                    <li class="">
                      <a href="#tab<%= work_unit.id %>" data-toggle="tab"><%=work_unit.name%></a>
                    </li>
                  <% end %>
                </tr>
                <hr>
              <% end %>
            </li>
          </table>                           
		  </ul>
    </div>
  </nav>
</div>

<!-- tab content -->
<div class="tab-content col-sm-10">
<div class="tab-pane active text-style" id="tab170">
  <h2>Médicos por unidade</h2>
  <hr> 
  <div style="overflow: auto; height: 460px">
    <table>
      <tr>
        <%= render partial: "workunits_graph" %>  
      </tr>
    </table>  
  </div>
</div>

<% @work_unit.each do |work_unit| %> 
  <div class="tab-pane text-style" id="tab<%= work_unit.id %>">
    <h2>Quantidade de médicos em <%= work_unit.name %></h2>
    <hr>
    <% @id = work_unit.id%>
    <% @array_speciality = array_speciality(work_unit.id) %>
    <% @array_quantity_medics = array_medics_quantity(work_unit.id, @array_speciality) %>
    <div style="overflow: auto; height: 460px">
      <table>
        <tr>
          <%= render partial: "quantity_medics_by_speciality" %>
        </tr>
      </table> 
    </div>
  </div>
<%end%>
    