config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  root 'home#index'
  match 'home', controller: 'home', action: 'index', via: 'get'
  get "/about" => "home#about", :as => "about" 

  match 'medics/results', controller: 'medics', action: 'results', via: 'get'
  match 'medics/rating', controller: 'medics', action: 'rating', via: 'post'
  match 'medics/create_comment', controller: 'medics', action: 'create_comment', via: 'post'
  match 'medics/create_relevance', controller: 'medics', action: 'create_relevance', via: 'post'
  get "/medics/profile/:id" => "medics#profile", :as => "profile"
  get "/workunits_graph" => "medics#workunits_graph", :as => "workunits_graph"
  match '/confirmation/:id/:token_email', controller: 'users', action: 'confirmation_email', via: 'get'

  get "/medics/profile/:id/create_relevance" => "medics#create_relevance", :as => "create_relevance"
  get "/medics/profile/:id/to_report" => "medics#to_report", :as => "to_report"

  get "/users/:id/edit_password" => "users#edit_password", :as => "edit_password"
  patch "/users/:id/edit_password/update_password", to: "users#update_password"
  
  get "/comments/reports", controller: 'comments', action: 'reports', :as => "reported_comments"
  get "/comments/reactivate_comment" => "comments#reactivate", :as => "reactivate_comment"
  get "/comments/deactivate_comment" => "comments#deactivate", :as => "deactivate_comment"
  get "/comments/disable_report" => "comments#disable_report", :as => "disable_report"
    
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "desactivate_account" => "users#desactivate", :as => "desactivate_account"
  get "/users/:id/reactivate_account" => "users#reactivate", :as => "reactivate_account"
  get "/users/:id/desactivate_account" => "users#desactivate", :as => "desactivate_account_admin"
  post "/upload", controller: 'parsers', action: 'upload'

  get "contact" => "contact#new", :as => "contact"

  post "/parsers", controller: 'parsers', action: 'index', :as => "index_parser"
  
  get 'users/index'
  get 'users/new'

  post '/users/:id', to: 'users#show'
  get '/users/:id/edit', to: 'users#edit'

  patch '/users/:id', to: 'users#update'

  resources :users do
    put :updatePassword, on: :member
  end
  resources :sessions
  resources :home
  resources :parsers
  resources :contact
  resources :password_resets

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :medic
	has_many :relevance

	validates :content, presence: true, length: { maximum: 300 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def reports
		@user = User.find_by_id(session[:remember_token])

      	if @user && @user.username == "admin"
			@reported_comments = Comment.all.where(report: true)
		else
			redirect_to root_path
		end
	end

	def deactivate
		@comment = Comment.find_by_id(params[:comment_id])
		if @comment
			@comment.update_attribute(:comment_status, false)
		end
		redirect_to reported_comments_path
	end

	def reactivate
		@comment = Comment.find_by_id(params[:comment_id])
		if @comment
			@comment.update_attribute(:comment_status, true)
		end
		redirect_to reported_comments_path
	end

	def disable_report
		@comment = Comment.find_by_id(params[:comment_id])
		if @comment
			@comment.update_attribute(:report, false)
		end
		redirect_to reported_comments_path
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/reports.html.erb
<br>
<br>
<div class="panel panel-default widget">
            <div class="panel-heading">

                <h3 class="panel-title">
                    Comentários Denúnciados</h3>
                <span class="label label-info">
                    <%= @reported_comments.size %></span>
</div>
<div class="panel-body">
    <ul class="list-group">
    	<% if @reported_comments.size == 0 %>
    		<li class="list-group-item">
    			Não há Denuncias
    		</li>
    	<% end %>
		<% @reported_comments.each do |reported_comment|%>
			<li class="list-group-item">
		        <div class="row">
		            <div class="col-xs-10 col-md-11">
		            	
		                <div class="reported_comment-text">
		                    <%= reported_comment.content%>
		                    <div class="btn-group report-btn-group" role="group" aria-label="...">
			                    <% if reported_comment.comment_status == false %>
									<%= link_to 'Reativar' , reactivate_comment_path(:comment_id => reported_comment.id) , class: "btn btn-primary activate" %>
								<% else %>
									<%= link_to 'Tirar Denúncia' , disable_report_path(:comment_id => reported_comment.id) , class: "btn btn-primary activate" %>
									<%= link_to 'Desativar' , deactivate_comment_path(:comment_id => reported_comment.id) , class: "btn btn-danger activate",  data: { confirm: 'Você tem certeza?' }%>
								<% end %>
							</div>
		                </div>
		                <div>
		                    <div class="mic-info">
		                        Autor: <%= reported_comment.user.username%> em <%= reported_comment.date.strftime("%d de %B de %Y")%>
		                        <br>
		                        Médico: <%= link_to reported_comment.medic.name, profile_path(reported_comment.medic)%>
		                    </div>
		                </div>
		            </div>
		        </div>
		    </li>
		<% end %>
	</ul>
</div>