config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  root 'home#index'
  match 'home', controller: 'home', action: 'index', via: 'get'
  get "/about" => "home#about", :as => "about" 

  match 'medics/results', controller: 'medics', action: 'results', via: 'get'
  match 'medics/rating', controller: 'medics', action: 'rating', via: 'post'
  match 'medics/create_comment', controller: 'medics', action: 'create_comment', via: 'post'
  match 'medics/create_relevance', controller: 'medics', action: 'create_relevance', via: 'post'
  get "/medics/profile/:id" => "medics#profile", :as => "profile"
  get "/workunits_graph" => "medics#workunits_graph", :as => "workunits_graph"
  match '/confirmation/:id/:token_email', controller: 'users', action: 'confirmation_email', via: 'get'

  get "/medics/profile/:id/create_relevance" => "medics#create_relevance", :as => "create_relevance"
  get "/medics/profile/:id/to_report" => "medics#to_report", :as => "to_report"

  get "/users/:id/edit_password" => "users#edit_password", :as => "edit_password"
  patch "/users/:id/edit_password/update_password", to: "users#update_password"
  
  get "/comments/reports", controller: 'comments', action: 'reports', :as => "reported_comments"
  get "/comments/reactivate_comment" => "comments#reactivate", :as => "reactivate_comment"
  get "/comments/deactivate_comment" => "comments#deactivate", :as => "deactivate_comment"
  get "/comments/disable_report" => "comments#disable_report", :as => "disable_report"
    
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "desactivate_account" => "users#desactivate", :as => "desactivate_account"
  get "/users/:id/reactivate_account" => "users#reactivate", :as => "reactivate_account"
  get "/users/:id/desactivate_account" => "users#desactivate", :as => "desactivate_account_admin"
  post "/upload", controller: 'parsers', action: 'upload'

  get "contact" => "contact#new", :as => "contact"

  post "/parsers", controller: 'parsers', action: 'index', :as => "index_parser"
  
  get 'users/index'
  get 'users/new'

  post '/users/:id', to: 'users#show'
  get '/users/:id/edit', to: 'users#edit'

  patch '/users/:id', to: 'users#update'

  resources :users do
    put :updatePassword, on: :member
  end
  resources :sessions
  resources :home
  resources :parsers
  resources :contact
  resources :password_resets

end

app/models/user.rb
require 'valid_email'
require 'bcrypt'

class User < ActiveRecord::Base
	has_many :comments
	has_many :relevance

	has_one :rating

	attr_accessor :password, :password_confirmation, :new_password, :document
	before_save :encrypt_password

	validates :username, uniqueness: true, presence: true
	validates :email, uniqueness: true, presence: true, email: true
	validates :password, presence: true
	validates :password_confirmation, presence: true
	validates :new_password, presence: true, :on => [:updatePassword]

	def self.authenticate(username, password)
		user = find_by_username_and_account_status(username,true)

		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password
	    if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	    end
  	end

  	def send_password_reset
	  generate_token(:password_reset_token)
	  self.password_reset_sent_at = Time.zone.now
	  update_attribute(:password_reset_token , password_reset_token)
	  UserMailer.password_reset(self).deliver
	end

	def generate_token(column)
	  begin
	    self[column] = SecureRandom.urlsafe_base64
	  end while User.exists?(column => self[column])
	end
end
 

app/controllers/users_controller.rb
require 'bcrypt'

class UsersController < ApplicationController
    def index
        @user = User.find_by_id(session[:remember_token])

      if @user && @user.username == "admin" 
        @users = User.all
      else
        redirect_to root_path
      end

  	end

  	def create
  		@user = User.new(user_params)
        if @user.account_status == false && !params[:user][:document]
            flash.now.alert = "Você precisa anexar um documento!"
            render "new"
        elsif  @user.password == @user.password_confirmation
            
            @user.account_status = false
            if @user.save
                upload params[:user][:document]
                
                if params[:user][:document] == nil
                    random = Random.new
                    @user.update_attribute(:token_email, random.seed)
                     @user.update_attribute(:medic_type_status, false)
                    TemdfMailer.confimation_email(@user.id, @user.token_email, @user.email).deliver
                    flash[:notice] = "Por favor confirme seu cadastro pela mensagem enviada ao seu email!"
                else
                    @user.update_attribute(:medic_type_status, true)
                    flash[:notice] = "Nossa equipe vai avaliar seu cadastro. Por favor aguarde a nossa aprovação para acessar sua conta!"
                end
                redirect_to root_path
            else
                render "new"
            end
        else
            render "new"
        end
  	end

  	def new
  		@user = User.new
  	end

    def edit
        @user = User.find_by_id(session[:remember_token])
    end

    def edit_password
        @user = User.find_by_id(session[:remember_token]) 
    end

    def update
      @user = User.find_by_id(session[:remember_token])

        if @user
          if @user.username == "admin" #admin's update
            email = params[:user][:email]

            user_from_email = User.find_by_email(email)

            if user_from_email && @user != user_from_email
                flash[:alert] = "Email já existente"
                render "edit" 
            else 
                @user.update_attribute(:email , email)
                redirect_to root_path, notice: 'Usuário alterado!'
            end

          else #commom user's update 
            username = params[:user][:username]
            email = params[:user][:email]

            user_from_username = User.find_by_username(username)
            user_from_email = User.find_by_email(email)

            if user_from_username && @user != user_from_username
                flash[:alert] = "Nome já existente"
                render "edit"
            elsif user_from_email && @user != user_from_email
                flash[:alert] = "Email já existente"
                render "edit" 
            else 
                @user.update_attribute(:username , username)
                @user.update_attribute(:email , email)
                redirect_to root_path, notice: 'Usuário alterado!'
            end
          end
        else
            redirect_to root_path
        end
    end

    def update_password
      @user_session = User.find_by_id(session[:remember_token])
      
        if @user_session
            @user = User.authenticate(@user_session.username, params[:user][:password])
            new_password = params[:user][:new_password]
            
            if params[:user][:password_confirmation] == new_password && !new_password.blank?
              @user.update_attribute(:password, new_password)
              redirect_to root_path, notice: 'Alteração feita com sucesso'
            else
              redirect_to edit_password_path, alert: 'Confirmação nao confere ou campo vazio'
            end
        else
          redirect_to edit_password_path
        end
    end
    
    def desactivate
        @user = User.find_by_id(session[:remember_token])

        if @user && @user.username != "admin"
            @user.update_attribute(:account_status, false)
            redirect_to logout_path
        else
          @user = User.find_by_id(params[:id])

          if @user
            @user.update_attribute(:account_status, false)
            redirect_to(action: "index")
          else
            redirect_to root_path
          end
        end
    end

     def reactivate
      @user = User.find_by_id(params[:id])
      if @user
        @user.update_attribute(:account_status, true)
        redirect_to(action: "index")
      else
        redirect_to root_path
      end
    end

    def confirmation_email

        @user = User.find_by_id_and_token_email(params[:id],params[:token_email])
        @message = ''

        if @user && @user.token_email
          @user.update_attribute(:account_status, true)
          @user.update_attribute(:token_email, nil)
          @message = "Cadastro Confirmado!"
        else
          @message = "Link inválido!"
        end
        redirect_to root_path, notice: @message
    end

    private
        def user_params
            params.require(:user).permit(:username, :email, :password, :password_confirmation, :account_status)
        end

        def upload(uploaded_io)
            if uploaded_io
                File.open(Rails.root.join('public', 'uploads', 'arquivo_medico'), 'wb') do |file| 
                    file.write(uploaded_io.read)
                end
                # send file to temdf email
                TemdfMailer.request_account.deliver
            end
        end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
<!-- user's register form-->
<div class="row">
  <div class="col-lg-6 col-md-offset-2">
<div class="panel panel-default">
    <div class="panel-heading">
        Novo Usuário
    </div>
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == 'notice' ? "success" : "danger" %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
    <div class="panel-body">
      <%= form_for(@user) do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %>
              prohibited this user from being saved:
            </h2>
            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <label>Tipo de usuário</label>
          <div class="radio">
            <label>
              <%= f.radio_button :account_status, true, :checked => false, :value => true%>
              Sou usuário do sistema público de saúde
            </label>
          </div>
          <div class="radio">
            <label>
              <%= f.radio_button :account_status, false, :checked => true, :value => false %>
              Sou médico do sistema público de saúde
            </label>
          </div>
        </div>
        <div class="form-group", id = "send_to_yes">
          <%= f.label "Por favor, selecione seu CRM para que possamos confirmar seu cadastro" %>
          <br>
          <%= f.file_field :document, accept: 'application/pdf'%>
        </div>        
        <div class="form-group">    
          <%= f.label :username %><br>
          <%= f.text_field :username , class: "form-control", :required => true%>
        </div>
        <div class="form-group">
          <%= f.label :email %><br>
          <%= f.text_field :email , class: "form-control", placeholder: "exemplo@exemplo.com", :required => true%>
        </div>
        <div class="form-group">
          <%= f.label :password %><br>
          <%= f.password_field :password , class: "form-control", :required => true%>
        </div>
        <div class="form-group">
            <%= f.label :password_confirmation %><br>
          <%= f.password_field :password_confirmation , class: "form-control", :required => true%>
        </div>
        <%= f.submit "Criar Usuario", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
<script>
$("input[type=radio]").change(function() {  
            if($(this).prop('value') == 'false'){
                    $("#send_to_yes").show();
                }
                else {
                    $("#send_to_yes").hide();
                }
        });
</script>

app/views/users/contact.html.erb
<%= form_tag("/contact", method: "get") do %> 
    <div class="input-group custom-search-form">
        <label>Especialidade</label>
        <input list="speciality" name="list_specility" class="form-control">
            <datalist id="speciality">
                <% @speciality.each do |speciality| %>
                    <option value="<%= speciality %>">
                <% end %>
            </datalist>
        </div>

        <div class="input-group custom-search-form">
        <label> Região </label>
        <input list="work_unit_name" name="list_work_unit_name" class="form-control">
            <datalist id="work_unit_name">
                <% @work_unit_name.each do |work_unit_name| %>
                    <option value="<%= work_unit_name %>">
                <% end %>
            </datalist>
        </div>

        <div>
            <br>
            <button type="submit" class="btn btn-default">Confirmar</button>
            <button type="reset" class="btn btn-default">Reset</button>
    </div>
<%end%>

app/views/users/edit.html.erb
<br>

<div class="col-lg-6 col-md-offset-2">
  <div class="panel panel-default">
    <div class="panel-heading">
        Editar Conta
    </div>
    <div class="panel-body">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name == 'notice' ? "success" : "danger" %>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>
      <%= form_for @user do |f| %>
        <% if @user.username != "admin" %>
          <div class="form-group">    
            <%= f.label :Nome %><br>
            <%= f.text_field :username, :required => true ,class: "form-control"%>
          </div>
        <% end %>

        <div class="form-group">    
          <%= f.label :Email %><br>
          <%= f.text_field :email, :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}',class: "form-control" %>
        </div>

        <%= f.submit 'Salvar alteração' , class: "btn btn-primary"%> 
        <%= link_to "Alterar Senha", edit_password_path, class: "btn btn-primary" %>
        
        <% if @user.username != "admin" %>
          <%= link_to "Desativar conta", desactivate_account_path ,class: "btn btn-danger" %>
        <% end %>  
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit_password.html.erb
<br>
<div class="row">
  <div class="col-lg-5 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
          Altere sua senha
      </div>
        <div class="panel-body">
          <%= form_for @user, :url => url_for(:controller => 'users', :action => 'update_password') do |f| %>

            <div class="form-group">
              <%= f.label :Senha_atual %><br>
              <%= f.password_field :password, :required => true , class: "form-control"%>
            </div>

            <div class="form-group">
              <%= f.label :Nova_senha %><br>
              <%= f.password_field :new_password ,:required => true , class: "form-control"%>
            </div>

            <div class="form-group">
              <%= f.label :Confirmação_da_senha %><br>
              <%= f.password_field :password_confirmation, :required => true , class: "form-control"%>
            </div>
            <%= f.submit 'Alterar Senha', class: "btn btn-primary" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.3/css/jquery.dataTables.css">
</head>
<h1>Usuários</h1>
<!-- <p>Find me in app/views/user/index.html.erb</p> -->

<div class="row">
	<div class="col-lg-12">
	  <div class="panel panel-default">
			<div class="table-responsive">
			  <table class="table table-striped table-bordered table-hover" id="dataTables">
				  <thead>
						<tr>
							<th>Username</th>
							<th>Email</th>
							<th>Estado da Conta</th>
							<th></th>
						</tr>	
					</thead>
					<tbody>
						<%@users.each do |user| %>
							<% if user.username != "admin"%>
								<tr>
									<td><%= user.username %></td>
									<td><%= user.email %></td>
									<td>
										<% if user.account_status == true %>
											Ativo
										<% else %>
											Inativo
										<% end %>
									</td>
									<td>										
										<% if user.account_status == false %>
										<%= link_to 'Reativar' , reactivate_account_path(user) , class: "btn btn-primary" %>
										<% else %>
										<%= link_to 'Desativar' , desactivate_account_admin_path(user) , class: "btn btn-primary" %>
										<% end %>
									</td>
								</tr>
							<% end %>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<script>
    $(document).ready(function() {
        $('#dataTables').dataTable();
    });
  </script>

app/views/users/new.html.erb
<br>

<%= render 'form' %>