config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  root 'home#index'
  match 'home', controller: 'home', action: 'index', via: 'get'
  get "/about" => "home#about", :as => "about" 

  match 'medics/results', controller: 'medics', action: 'results', via: 'get'
  match 'medics/rating', controller: 'medics', action: 'rating', via: 'post'
  match 'medics/create_comment', controller: 'medics', action: 'create_comment', via: 'post'
  match 'medics/create_relevance', controller: 'medics', action: 'create_relevance', via: 'post'
  get "/medics/profile/:id" => "medics#profile", :as => "profile"
  get "/workunits_graph" => "medics#workunits_graph", :as => "workunits_graph"
  match '/confirmation/:id/:token_email', controller: 'users', action: 'confirmation_email', via: 'get'

  get "/medics/profile/:id/create_relevance" => "medics#create_relevance", :as => "create_relevance"
  get "/medics/profile/:id/to_report" => "medics#to_report", :as => "to_report"

  get "/users/:id/edit_password" => "users#edit_password", :as => "edit_password"
  patch "/users/:id/edit_password/update_password", to: "users#update_password"
  
  get "/comments/reports", controller: 'comments', action: 'reports', :as => "reported_comments"
  get "/comments/reactivate_comment" => "comments#reactivate", :as => "reactivate_comment"
  get "/comments/deactivate_comment" => "comments#deactivate", :as => "deactivate_comment"
  get "/comments/disable_report" => "comments#disable_report", :as => "disable_report"
    
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "desactivate_account" => "users#desactivate", :as => "desactivate_account"
  get "/users/:id/reactivate_account" => "users#reactivate", :as => "reactivate_account"
  get "/users/:id/desactivate_account" => "users#desactivate", :as => "desactivate_account_admin"
  post "/upload", controller: 'parsers', action: 'upload'

  get "contact" => "contact#new", :as => "contact"

  post "/parsers", controller: 'parsers', action: 'index', :as => "index_parser"
  
  get 'users/index'
  get 'users/new'

  post '/users/:id', to: 'users#show'
  get '/users/:id/edit', to: 'users#edit'

  patch '/users/:id', to: 'users#update'

  resources :users do
    put :updatePassword, on: :member
  end
  resources :sessions
  resources :home
  resources :parsers
  resources :contact
  resources :password_resets

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Trânsparencia em Escalas Médicas" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    <title>Trânsparencia em Escalas Médicas</title>

    <%= favicon_link_tag(source='logo.ico', options={}) %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to root_path, :class => "navbar-brand" do %>
                    <%= image_tag "logo_navbar.png" %>
                <% end %>
            </div>
            <!-- /.navbar-header -->

            <ul class="title">
                Transparência em Escalas Médicas do DF
            </ul>

            <ul class="nav navbar-top-links navbar-right">
                <% if current_user %>
                    <li class="dropdown">
                        <a class="dropdown-toggle" value="admin" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i> <%= current_user.username %><i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <%= link_to edit_user_path(session[:remember_token]) do %>
                                    <i class="fa fa-user fa-fw"></i> Editar Perfil
                                <% end %>
                            </li>
                            <% if current_user.username == "admin"%>
                                <li>
                                    <%= link_to users_path do %>
                                        <i class="fa fa-users fa-fw"></i> Usuários
                                    <% end %>
                                </li>
                                <li>
                                    <%= link_to index_parser_path do %>
                                        <i class ="fa fa-cloud-upload fa-fw"></i> Carregar Dados
                                    <% end %>
                                </li>
                                <li>
                                    <%= link_to reported_comments_path do %>
                                        <i class="fa fa-exclamation fa-fw"></i> Denúncias
                                    <% end %>
                                </li>
                            <% end %>
                            <li class="divider"></li>
                            <li>
                                <%= link_to logout_path do %>
                                    <i class="fa fa-sign-out fa-fw"></i> Sair
                                <% end %>
                            </li>
                        </ul>
                        <!-- /.dropdown-user -->
                    </li>
                <% else %>
                    <li><%= link_to "Entrar", login_path %></li>
                    <li><%= link_to "Cadastrar", new_user_path %></li>
                <% end %>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <% flash.each do |name, msg| %>
                                  <% if msg.is_a?(String) && msg != "O Usuário necessita estar logado" && msg != "Usuário ou senha inválidos" && msg != "Você precisa anexar um documento!" %>
                                    <div class="alert alert-<%= name == 'notice' ? "success" : "danger" %>">
                                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                      <%= content_tag :div, msg, :id => "flash_#{name}" %>
                                    </div>
                                  <% end %>
                                <% end %>
                                <%= form_tag("/medics/results", method: "get") do %>

                                    <div class="input-group custom-search-form">
                                        <label>Especialidade</label>
                                        <select name="list_specility" class="form-control">
                                            <option>Informe a Especialidade</option>
                                            <% list_speciality.each do |speciality| %>
                                                <option value="<%= speciality %>">
                                                    <%= speciality %>
                                                </option>
                                            <% end %>
                                        </select>
                                    </div>

                                    <div class="input-group custom-search-form">
                                        <label> Região </label>
                                        <select name="list_work_unit_name" class="form-control">
                                            <option>Informe a Região</option>
                                            <% list_work_unit_name.each do |work_unit_name| %>
                                                <option value="<%= work_unit_name %>">
                                                    <%= work_unit_name %>
                                                </option>
                                            <% end %>
                                        </select>
                                    </div>

                                    <div class="btn-group app-btn-group" role="group" aria-label="...">
                                        <button type="submit" class="btn btn-primary app-btn">Confirmar</button>
                                        <button type="reset" class="btn btn-primary app-btn">Limpar</button>
                                    </div>
                                <%end%>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <%= link_to workunits_graph_path do %>
                                <i class="fa fa-bar-chart-o fa-fw"></i>
                                Gráficos
                            <%end%>
                        </li>
                        <li>
                            <%= link_to ranking_path do%>
                                <i  class="fa fa-star fa-fw"></i>
                                Ranking
                            <%end%>
                        </li>
                        <li>
                            <%= link_to contact_path do %>
                                <i  class="fa fa-envelope-o fa-fw"></i>
                                Contato
                            <%end%>
                        </li>
                        <li>
                            <%= link_to about_path do%>
                                <i  class="fa fa-info fa-fw"></i>
                                Sobre
                            <%end%>
                        </li>
                    </ul>
                    <!--<div align="center">-->
                </div>
               
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                   <%= yield %>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div><!-- /container -->

  </body>
</html>